spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-short?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Sgwmbhszj+1!

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# JWT配置
jwt:
  secret: airticketSecretKeyMustBeLongEnoughForHS256Algorithm
  expiration: 86400000
  refresh-expiration: 604800000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  file:
    location: /Users/sdongmaker/IdeaProjects/xiaolispringboot/moudl_campus/src/main/resources/static/upload